config/routes.rb
Rails.application.routes.draw do

  resources :scores do
    collection do
      put :discontinue
    end
  end

  resources :tests do
    collection do
      put :discontinue
    end
  end
  resources :subjects
  resources :periods do
    collection do
      put :discontinue
    end
  end


  resources :weeks
  devise_for :users
  resources :students
  resources :groups
  get 'home/about'

  # Set index as homepage
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Custom root
  get 'home/select'
  get 'home/timetable'
  get 'home/resulttable'
  get 'home/new_test'
  get 'home/edit_results'
  get 'home/show_results'
  get 'home/construction'
  get 'home/login_students'
  get 'home/index_teachers'
  get 'home/show_absences'
end

app/models/student.rb
class Student < ApplicationRecord
	has_many :periods
	has_many :scores
	belongs_to :group, optional: true
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
    @weeks = Week.all
    if(params.has_key?(:id))
      @id = params[:id]
    end

    @periods = Period.where(:student_id => Student.find(@id)).where("state > 0")
    @weeks = Week.all
    #@agg_periods = @periods.group(['week_id', 'id'])
    @agg_periods_abs= @periods.where(:state => 2).group('week_id').count
    @agg_periods_ret= @periods.where(:state => 1).group('week_id').count
    @tot_abs = @periods.where(:state => 2).count
    @tot_ret = @periods.where(:state => 1).count

    @student = Student.find(@id)
    @tests = Test.where(:group_id => @student.class_id)
    @subjects = @tests.distinct.pluck(:subject_id)
    @scores = Score.where(:student_id => Student.find(@id))
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        c=0
        Week.all.each do |week|
          c = c + 1
          for d in 1..5
            for i in 1..7
              Period.create([{ week_id: week.id, day: d, student_id: @student.id, state: 0 }])
            end
          end
          puts  c.to_s + "/" + (52).to_s

        format.html { redirect_to @student, notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      end

      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    Period.where(:student_id => @student.id).destroy_all

    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:first_name, :last_name, :email, :phone, :class_name)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_absences.html.erb
<h5>Rapport des absences</h5>
<table class='table table-striped table-hover'>
  <thead class='table-dark'>
    <tr>
      <th>Semaine</th>
      <th>Retards</th>
      <th>Absences</th>
    </tr>
  </thead>

  <tbody>

    <% @weeks.each do |w| %>
    	<% if @agg_periods_ret[w.id] != nil or @agg_periods_abs[w.id] != nil%>
	      <tr>
	        <td><%= w.date_formated %></td>
	        <td><%= @agg_periods_ret[w.id] %></td>
	        <td><%= @agg_periods_abs[w.id] %></td>
	      </tr>
	    <% end %>
    <% end %>
  </tbody>
  <tfoot>
  	<tr>
  		<td></td>
  		<td><%= @tot_ret%></td>
  		<td><%= @tot_abs%></td>
  	</tr>
  </tfoot>
</table>

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>
      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field form-group">
    <% form.label :first_name %>
    <%= form.text_field :first_name, class:'form-control', placeholder:'Prénom' %>
  </div>
  <br />

  <div class="field form-group">
    <% form.label :last_name %>
    <%= form.text_field :last_name, class:'form-control', placeholder:'Nom' %>
  </div>
  <br />

  <div class="field form-group">
    <% form.label :email %>
    <%= form.text_field :email, class:'form-control', placeholder:'Email' %>
  </div>
  <br />

  <div class="field form-group">
    <% form.label :phone %>
    <%= form.text_field :phone, class:'form-control', placeholder:'Téléphone' %>
  </div>
  <br />

  <div class="field form-group">
    <% form.label :serial_num %>
    <%= form.text_field :serial_num, class:'form-control', placeholder:'Matricule' %>
  </div>
  <br />

  <div class="field form-group">
    <% form.label :class %>
    <%= form.collection_select :class_name, Group.all, :name, :name, {include_blank: false}, {class: 'form-control '} %>
  </div>

  <br />
  <div class="actions">
    <%= form.submit "Mettre à jour", class:'btn btn-primary' %>
  </div>
<% end %>

app/views/students/_results.html.erb
<h5>Rapport des résultats</h5>
<table class='table table-striped table-hover'>
  <thead class='table-dark'>
    <tr>
      <th>Branches</th>
      <th class='text-center' colspan=2>Résultats</th>
    </tr>
    <tr>
      <th></th>
      <th class='text-center'>Ecrits</th>
      <th class='text-center'>Oraux</th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |sub| %>
      <tr>
          <td>
                <%= Subject.find(sub).name %>
          </td>
          <td class='text-center'>
            <% scores_wrt = Score.where(:student_id => @id).where(:test_id => @tests.where(:subject_id => sub).where(:test_type => 0)) %>
            <% scores_orl = Score.where(:student_id => @id).where(:test_id => @tests.where(:subject_id => sub).where(:test_type => 1)) %>
            <% avg_wrt = scores_wrt.average(:score) %>
            <% avg_orl = scores_orl.average(:score) %>
            <% if avg_wrt.nil? %>
              <span class="text-muted">na</span>
            <%else%>
              <% if avg_wrt  >= 4 %>
                <span class="text-success"><%= avg_wrt.round(2) %></span>
              <% else %>
                <span class="text-danger"><%= avg_wrt.round(2) %></span>
              <% end %>
            <%end%>
          </td>
            
          <td class='text-center'>
            <% if avg_orl.nil? %>
                <span class="text-muted">na</span>
              <%else%>
                <% if avg_orl  >= 4 %>
                  <span class="text-success"><%= avg_orl.round(2) %></span>
                <% else %>
                  <span class="text-danger"><%= avg_orl.round(2) %></span>
                <% end %>
              <%end%>
          </td>
      </tr>
    <% end %>
    
  </tbody>
  <tfoot>
  	
  </tfoot>
</table>

app/views/students/edit.html.erb
<div class="card">
  <div class="card-header">
    <h4>Modifier l'étudiant</h4>
  </div>
  <div class="card-body">
    <%= render 'form', student: @student %>
  </div>
</div>

<br />
<%= link_to 'Voir', @student %>
<br/>
<%= link_to 'Retour', students_path %>

app/views/students/index.html.erb
<h4>Étudiants</h4>

<table class='table table-striped table-hover'>
  <thead class='table-dark'>
    <tr>
      <th>Prénom</th>
      <th>Nom</th>
      <th>Email</th>
      <th>Téléphone</th>
      <th>Classe</th>
      <th>Matricule</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @students.each do |student| %>
      <tr>
        <td><%= student.first_name %></td>
        <td><%= student.last_name %></td>
        <td><%= student.email %></td>
        <td><%= student.phone %></td>
        <td><%= student.class_name %></td>
        <td><%= student.serial_num %></td>
        <td>
          <%= link_to student  do%>
            <i class="bi bi-eye-fill btn btn-outline-secondary btn-sm"></i>
          <% end %>
        </td>

        <td>
          <%= link_to edit_student_path(student) do%>
            <i class="bi bi-pencil-fill btn btn-outline-secondary btn-sm"></i>
          <% end %>
        </td>
        <td>
          <%= link_to student, method: :delete, data: { confirm: 'Êtes-vous sûr de vouloir supprimer?' } do%>
            <i class="bi bi-trash-fill btn btn-outline-danger btn-sm"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Ajouter un étudiant', new_student_path, class:'btn btn-primary' %>
<br/>
<br/>
<%= link_to 'Séléctionner une classe', home_select_path %>

app/views/students/new.html.erb
<div class="card">
  <div class="card-header">
    <h4>Nouvel étudiant</h4>
  </div>
  <div class="card-body">
    <%= render 'form', student: @student %>
  </div>
</div>

<br />

<%= link_to 'Retour', students_path%>

app/views/students/show.html.erb
<div class="card">
  <div class="card-header">
    <h4><%= @student.first_name %> <%= @student.last_name %> <span class="badge bg-dark text-light"><%= @student.class_name %></span></h4>
  </div>
  <div class="card-body">
    <%= @student.email %> | <%= @student.phone %>
    <br />
    <br />
    <%= link_to 'Modifier', edit_student_path(@student), class:'btn btn-primary' %>
  </div>
</div>
<br/>

<%= render 'students/absences' %> 

<%= render 'students/results' %>


<%= link_to 'Retour', students_path%>