config/routes.rb
Rails.application.routes.draw do

  resources :scores do
    collection do
      put :discontinue
    end
  end

  resources :tests do
    collection do
      put :discontinue
    end
  end
  resources :subjects
  resources :periods do
    collection do
      put :discontinue
    end
  end


  resources :weeks
  devise_for :users
  resources :students
  resources :groups
  get 'home/about'

  # Set index as homepage
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Custom root
  get 'home/select'
  get 'home/timetable'
  get 'home/resulttable'
  get 'home/new_test'
  get 'home/edit_results'
  get 'home/show_results'
  get 'home/construction'
  get 'home/login_students'
  get 'home/index_teachers'
  get 'home/show_absences'
end

app/models/score.rb
class Score < ApplicationRecord
	belongs_to :test
	belongs_to :student
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :set_score, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /scores or /scores.json
  def index
    @scores = Score.all
  end

  # GET /scores/1 or /scores/1.json
  def show
  end

  # GET /scores/new
  def new
    @score = Score.new
  end

  # GET /scores/1/edit
  def edit
  end

  # POST /scores or /scores.json
  def create
    @score = Score.new(score_params)

    respond_to do |format|
      if @score.save
        format.html { redirect_to @score, notice: "Score was successfully created." }
        format.json { render :show, status: :created, location: @score }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scores/1 or /scores/1.json
  def update
    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to @score, notice: "Score was successfully updated." }
        format.json { render :show, status: :ok, location: @score }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1 or /scores/1.json
  def destroy
    @score.destroy
    respond_to do |format|
      format.html { redirect_to scores_url, notice: "Score was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def discontinue
    #skip_before_action :verify_authenticity_token

    value = params[:score]
    if value.to_f >= 1 and value.to_f <= 6
      Score.find(params[:id]).update(:score => value)
    else
      Score.where(id:params[:id]).update_all(:score => nil)
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def score_params
      params.require(:score).permit(:score, :student_id, :test_id)
    end
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/scores/_form.html.erb
<%= form_with(model: score) do |form| %>
  <% if score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
        <% score.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :score %>
    <%= form.text_field :score %>
  </div>

  <div class="field">
    <%= form.label :student_id %>
    <%= form.number_field :student_id %>
  </div>

  <div class="field">
    <%= form.label :test_id %>
    <%= form.number_field :test_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/scores/edit.html.erb
<h1>Editing Score</h1>

<%= render 'form', score: @score %>

<%= link_to 'Show', @score %> |
<%= link_to 'Back', scores_path %>

app/views/scores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Scores</h1>

<table>
  <thead>
    <tr>
      <th>Score</th>
      <th>Student</th>
      <th>Test</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scores.each do |score| %>
      <tr>
        <td><%= score.score %></td>
        <td><%= score.student_id %></td>
        <td><%= score.test_id %></td>
        <td><%= link_to 'Show', score %></td>
        <td><%= link_to 'Edit', edit_score_path(score) %></td>
        <td><%= link_to 'Destroy', score, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Score', new_score_path %>

app/views/scores/new.html.erb
<h1>New Score</h1>

<%= render 'form', score: @score %>

<%= link_to 'Back', scores_path %>

app/views/scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Score:</strong>
  <%= @score.score %>
</p>

<p>
  <strong>Student:</strong>
  <%= @score.student_id %>
</p>

<p>
  <strong>Test:</strong>
  <%= @score.test_id %>
</p>

<%= link_to 'Edit', edit_score_path(@score) %> |
<%= link_to 'Back', scores_path %>