config/routes.rb
Rails.application.routes.draw do

  resources :scores do
    collection do
      put :discontinue
    end
  end

  resources :tests do
    collection do
      put :discontinue
    end
  end
  resources :subjects
  resources :periods do
    collection do
      put :discontinue
    end
  end


  resources :weeks
  devise_for :users
  resources :students
  resources :groups
  get 'home/about'

  # Set index as homepage
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Custom root
  get 'home/select'
  get 'home/timetable'
  get 'home/resulttable'
  get 'home/new_test'
  get 'home/edit_results'
  get 'home/show_results'
  get 'home/construction'
  get 'home/login_students'
  get 'home/index_teachers'
  get 'home/show_absences'
end

app/models/group.rb
class Group < ApplicationRecord
	has_many :students
	has_many :tests
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: [:login_students, :index]
  def index
  end

  def about
  end


  def select
  	@groups = Group.all
  end

  def timetable

  	@current_week = Week.where("start_date <= :today AND end_date >= :today", {today: DateTime.current.to_date}).first
    @current_day = (DateTime.current.to_date - @current_week.start_date).to_i + 1
  	if(params.has_key?(:class))
      gr = params[:class]
      @requested_class = Group.where(id:gr).first
      @students = Student.where(class_name:@requested_class.name)
    else
      #@students = Student.all.order('last_name')
      gr = Group.first.name
      @requested_class = Group.first
      @students = Student.where(class_name:@requested_class.name)
    end


    if(params.has_key?(:week))
      wk = params[:week]
      @requested_week = Week.where(id:wk).first
    else
      wk = @current_week.id
      @requested_week = @current_week
    end

    if(params.has_key?(:day))
      dy = params[:day].to_i
      if(dy >= 6)
        dy = 5
      end
      @requested_day = dy

    else
      if(@current_day >= 6)
        @requested_day = 1
      else
        @requested_day = @current_day
      end
    end

    #@periods = Period.where("week_id = :week AND (student_id IN :student)", {week: wk, student: @students.ids})
    @periods = Period.where(:week_id => wk).where(:day => @requested_day).where(:student_id => @students.ids)
  	
  	
  end

  def resulttable

    if(params.has_key?(:class))
      gr = params[:class]
      @requested_class = Group.where(id:gr).first
      @students = Student.where(class_name:@requested_class.name)
    else
      #@students = Student.all.order('last_name')
      gr = Group.first.name
      @requested_class = Group.first
      @students = Student.where(class_name:@requested_class.name)
    end


    if(params.has_key?(:sub))
      sb = params[:sub]
      @requested_subject = Week.where(id:wk).first

    else
      @requested_week = @current_week
    end

    if(params.has_key?(:day))
      dy = params[:day]
      @requested_day = dy.to_i

    else
      @requested_day = @current_day
    end

    #@periods = Period.where("week_id = :week AND (student_id IN :student)", {week: wk, student: @students.ids})
    @periods = Period.where(:week_id => wk).where(:day => @requested_day).where(:student_id => @students.ids)
    
    
  end

  def new_test
    @groups = Group.all

  end

  def edit_results
    ts = params[:test_ids].map(&:to_i)
    @requested_tests = Test.where(id:ts)

    if(params.has_key?(:class))
      @gr = params[:class]

    else
      @gr = @requested_tests.first.group_id
    end

    @requested_test = @requested_tests.where(:group_id => @gr)
    @students = Student.joins(:scores).where(scores: {:test_id => @requested_test.ids}).order(:last_name)
    
    @requested_scores = Score.where(:test_id => @requested_test.ids)


  end

  def show_results
    @groups = Group.all
    if(params.has_key?(:class))
      @gr = params[:class]
    else
      @gr = Group.first.id
    end

    @tests = Test.where(:group_id => @gr)
    @subjects = @tests.distinct.pluck(:subject_id)
    @students = Student.where(:class_name => Group.find(@gr).name).order(:last_name)
  end

  def login_students
    @weeks = Week.all
    if(params.has_key?(:mat))
      @mat = params[:mat]
    end

    @periods = Period.where(:student_id => Student.where(:serial_num => @mat).ids).where("state > 0")
    @weeks = Week.all
    #@agg_periods = @periods.group(['week_id', 'id'])
    @agg_periods_abs= @periods.where(:state => 2).group('week_id').count
    @agg_periods_ret= @periods.where(:state => 1).group('week_id').count
    @tot_abs = @periods.where(:state => 2).count
    @tot_ret = @periods.where(:state => 1).count
  end

  def index_teachers
  end

  def show_absences
    @groups = Group.all
    if(params.has_key?(:class))
      @gr = params[:class]
    else
      @gr = Group.first.id
    end


    @students = Student.where(:class_name => Group.find(@gr).name).order(:last_name)

    
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  	<%= link_to 'Spart', root_path, class:'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <% if user_signed_in? %>
	        <li class="nav-item">
	          <%= link_to 'Mon Profil', edit_user_registration_path, class:'nav-link' %>
	        </li>
	        <li class="nav-item">
	          <%= link_to 'Déconnexion', destroy_user_session_path, method: :delete, class:'nav-link' %>
	        </li>
	      	<li class="nav-item">
	          <%= link_to 'Etudiants', students_path, class:'nav-link' %>
	        </li>
          <li class="nav-item">
            <%= link_to 'Absences', home_timetable_path, class:'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Rapport', home_show_absences_path, class:'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Épreuves', tests_path, class:'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Résultats', home_show_results_path, class:'nav-link' %>
          </li>
	        <li class="nav-item">
	          <%= link_to 'A propos', home_about_path, class:'nav-link' %>
	        </li>
	    <% else %>
	    	<li class="nav-item">
          	  <%= link_to 'Connexion', new_user_session_path, class:'nav-link' %>
        	</li>
        	<li class="nav-item">
	          <%link_to 'Enregistrement', new_user_registration_path, class:'nav-link' %>
	        </li>
        <% end %>

      </ul>
      
    </div>
  </div>
</nav>

app/views/home/_schedule.html.erb
<table class='table table-striped table-borderless table-responsive'>
  <thead class='table-dark'>
    <tr>
      <th>Nom</th>
      <th>Prénom</th>
      <th>Classe</th>
      <% days = ['Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi'] %>

	  	<th colspan="8" class='text-center'>
	  		<%= days[@requested_day - 1] + " " + (@requested_week.start_date + @requested_day - 1).strftime("%d.%m") %>
	    </th>

    </tr>
    <tr>
      <th></th>
      <th></th>
	  <th></th>
	  	  <% periods = ['8h30 - 10h00', '10h20 - 11h05', '11h15 - 12h00', '12h00 - 12h45', '13h45 - 14h30', '14h30 - 15h15', '15h30 - 16h15'] %>
	  		<% for i in 0..6 %>
  				<th class='text-center'>
            		<%= periods[i] %>
          		</th>
      		<% end %>
	    

    </tr>
  </thead>

  <tbody>

    <% #@periods.group(:student_id).each do |s| %>
    <% @students.order(:last_name).each do |s| %>
      <tr>
        <td>
          <%= s.last_name %>
        </td>
        <td>
          <%= s.first_name %>
        </td>
        <td>
          <%= s.class_name %>
        </td>
        
        <% @periods.where(:student_id => s.id).order(:id).each do |p| %>
          <td class='text-center'>

            <div class="btn-group" role="group" aria-label=<%= p.id %>>
              <% 
                id_r = p.id.to_s + "_R"
                if p.state == 1
                  state_a = true
                else
                  state_a = false
                end
              %>

              <%= radio_button_tag "period_ids_r[]", p.id, state_a, autocomplete:"off", class:"btn-check", type:"checkbox", id:id_r %>
              <%= label_tag id_r, "R", class: "btn btn-outline-warning" %>

              <%
                id_a = p.id.to_s + "_A"
                if p.state == 2 
                  state_r = true
                else
                  state_r = false
                end
              %>


              <%= radio_button_tag "period_ids_a[]", p.id, state_r, autocomplete:"off", class:"btn-check", type:"checkbox", id:id_a %>
              <%= label_tag id_a, "A", class: "btn btn-outline-danger" %>

              
            </div>

          </td>
        <% end %>
        
      </tr>
    <% end %>

  </tbody>
</table>

<%= hidden_field_tag 'week', @requested_week.id %>
<%= hidden_field_tag 'day', @requested_day %>
<%= hidden_field_tag 'class', @requested_class.id %>
<%= submit_tag "Enregistrer", class: "btn btn-success", id:"liveToastBtn", onclick: "toastr.success('Appel enregistré')"%>

app/views/home/_schedule1.html.erb
<table class='table table-striped table-borderless table-responsive'>
  <thead class='table-dark'>
    <tr>
      <th>Nom</th>
      <th>Prénom</th>
      <th>Classe</th>
      <% days = ['Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi'] %>

	  	<th colspan="8" class='text-center'>
	  		<%= days[@requested_day - 1] + " " + (@requested_week.start_date + @requested_day - 1).strftime("%d.%m") %>
	    </th>

    </tr>
    <tr>
      <th></th>
      <th></th>
	  <th></th>
	  	  <% periods = ['8h30 - 10h00', '10h20 - 11h05', '11h15 - 12h00', '12h00 - 12h45', '13h45 - 14h30', '14h30 - 15h15', '15h30 - 16h15'] %>
	  		<% for i in 0..6 %>
  				<th class='text-center'>
            		<%= periods[i] %>
          		</th>
      		<% end %>
	    

    </tr>
  </thead>

  <tbody>

    <% @periods.group(:student_id).each do |s| %>
      <tr>
        <td>
          <%= s.student.last_name %>
        </td>
        <td>
          <%= s.student.first_name %>
        </td>
        <td>
          <%= s.student.class_name %>
        </td>
        
        <% @periods.where( :student_id => s.student.id).each do |p| %>
          <td class='text-center'>

            <div class="btn-group" role="group" aria-label=<%= p.id %>>
              <% 
                id_r = p.id.to_s + "_R"
                if p.state == 1
                  state_a = true
                else
                  state_a = false
                end
              %>

              <%= radio_button_tag "period_ids_r[]", p.id, state_a, autocomplete:"off", class:"btn-check", type:"checkbox", id:id_r %>
              <%= label_tag id_r, "R", class: "btn btn-outline-warning" %>

              <%
                id_a = p.id.to_s + "_A"
                if p.state == 2 
                  state_r = true
                else
                  state_r = false
                end
              %>


              <%= radio_button_tag "period_ids_a[]", p.id, state_r, autocomplete:"off", class:"btn-check", type:"checkbox", id:id_a %>
              <%= label_tag id_a, "A", class: "btn btn-outline-danger" %>

              
            </div>

          </td>
        <% end %>
        
      </tr>
    <% end %>

  </tbody>
</table>

<%= hidden_field_tag 'week', @requested_week.id %>
<%= submit_tag "Enregistrer", class: "btn btn-success", id:"liveToastBtn", onclick: "toastr.success('Appel enregistrer')"%>

app/views/home/_selection.html.erb
<div class="card">
  <div class="card-header">
    <h4>Séléctioner une classe</h4>
  </div>
  <div class="card-body">
    <%= form_with url: "/home/timetable", method: :get do |form| %>
      <%= form.collection_select :week, Week.all, :id, :date_formated, {:selected => @requested_week.id}, {class: 'form-control '} %>
    </br>
      <%= form.collection_select :class, Group.all, :id, :name, {:selected => @requested_class.id}, {class: 'form-control '} %>
    </br>
      <%= form.submit "Exécuter", class:"btn btn-primary" %>
  <% end %>
  </div>
</div>

app/views/home/_selection_class.html.erb
<div class="card">
  <div class="card-header">
    <h4>Séléctioner une classe</h4>
  </div>
  <div class="card-body">
    <%= form_with url: "/home/resulttable", method: :get do |form| %>
      <%= form.collection_select :class, Group.all, :id, :name, {:selected => @requested_class.id}, {class: 'form-control '} %>
    </br>
      <%= form.submit "Exécuter", class:"btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/home/_selection_day1.html.erb
<% days = ['Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi'] %>
<br/><br/>
<ul class="nav nav-tabs">
	<% for i in 0..4 %>
		<li class="nav-item">
			<% if i == @requested_day -1 %>
				<%= link_to days[i], params.permit(:week, :class, :day).merge(:week => @requested_week, :class => @requested_class, :day => i + 1), class:"nav-link active" %>
			<% else %>
				<%= link_to days[i], params.permit(:week, :class, :day).merge(:week => @requested_week, :class => @requested_class, :day => i + 1), class:"nav-link" %>
			<% end %>
		</li>
  	<% end %>
  	<%= link_to "Aujourd'hui", params.permit(:week, :class, :day).merge(:week => @current_week.id, :class => @requested_class, :day => @current_day), class:"btn btn-primary" %>
</ul>

app/views/home/_selection_week.html.erb
<div class="card">
  <div class="card-header">
    <h4>Séléctioner une autre semaine ou classe</h4>
  </div>
  <div class="card-body">
    <%= form_with url: "/home/timetable", method: :get do |form| %>
      <%= form.collection_select :week, Week.all, :id, :date_formated, {:selected => @requested_week.id}, {class: 'form-control '} %>
    </br>
      <%= form.collection_select :class, Group.all, :id, :name, {:selected => @requested_class.id}, {class: 'form-control '} %>
    </br>
      <%= form.submit "Exécuter", class:"btn btn-primary" %>
  <% end %>
  </div>
</div>

app/views/home/about.html.erb
<h1>About us</h1>

app/views/home/construction.html.erb
<h4>Cette section est en cours de développement</h4>

app/views/home/index.html.erb
<h1>Bienvenue</h1>

<div class="card">
  <div class="card-header">
    <h4>Je suis</h4>
  </div>
  <div class="card-body">
    <%= link_to "Étudiant", "/home/login_students", class:"btn btn-primary btn-lg w-100" %>
	<br/>
	<br/>
	<%= link_to "Enseignant", "/home/index_teachers", class:"btn btn-secondary btn-lg w-100" %>
  </div>
</div>

app/views/home/resulttable.html.erb
<h4>Result table</h4>

<%= render 'home/selection_class' %> 

<table class='table table-striped table-borderless table-responsive'>
  <thead class='table-dark'>
    <tr>
      <th>Nom</th>
      <th>Prénom</th>
      <th>Classe</th>
      <% subjects = ['Mathématiques', 'Physique', 'Chimie', 'Biologie', 'Histoire', 'Géographie', 'Français', 'Langue étrangère']%>

	  	<th colspan="8" class='text-center'>
	  		
	    </th>

    </tr>
    <tr>
      <th></th>
      <th></th>
	  <th></th>
	  	  <% periods = ['8h30 - 10h00', '10h20 - 11h05', '11h15 - 12h00', '12h00 - 12h45', '13h45 - 14h30', '14h30 - 15h15', '15h30 - 16h15'] %>
	  		<% for i in 0..6 %>
  				<th class='text-center'>
            		<%= periods[i] %>
          		</th>
      		<% end %>
	    

    </tr>
  </thead>

  <tbody>

    <% @periods.group(:student_id).each do |s| %>
      <tr>
        <td>
          <%= s.student.last_name %>
        </td>
        <td>
          <%= s.student.first_name %>
        </td>
        <td>
          <%= s.student.class_name %>
        </td>
        
        <% @periods.where( :student_id => s.student.id).each do |p| %>
          <td class='text-center'>

            <div class="btn-group" role="group" aria-label=<%= p.id %>>
              <% 
                id_r = p.id.to_s + "_R"
                if p.state == 1
                  state_a = true
                else
                  state_a = false
                end
              %>

              <%= radio_button_tag "period_ids_r[]", p.id, state_a, autocomplete:"off", class:"btn-check", type:"checkbox", id:id_r %>
              <%= label_tag id_r, "R", class: "btn btn-outline-warning" %>

              <%
                id_a = p.id.to_s + "_A"
                if p.state == 2 
                  state_r = true
                else
                  state_r = false
                end
              %>


              <%= radio_button_tag "period_ids_a[]", p.id, state_r, autocomplete:"off", class:"btn-check", type:"checkbox", id:id_a %>
              <%= label_tag id_a, "A", class: "btn btn-outline-danger" %>

              
            </div>

          </td>
        <% end %>
        
      </tr>
    <% end %>

  </tbody>
</table>

app/views/home/show_absences.html.erb
<h4>Rapport des absences</h4>


<ul class="nav nav-tabs">
<% @groups.each do |group| %>
	<li class="nav-item">
	    <% if group.id == @gr.to_i %>
	    	<%= link_to group.name, params.permit(:class).merge(:class => group.id) , class:"nav-link active" %>
	    <% else %>
	    	<%= link_to group.name, params.permit(:class).merge(:class => group.id) , class:"nav-link" %>
	    <% end %>
  	</li>
<% end %>
</ul>

<table class='table table-striped table-responsive table-hover'>
  <thead class='table-dark'>
    <tr>
      <th>Étudiant</th>
      <th>Classe</th>
	  	<th>Retards</th>
      <th>Absences</th>
    </tr>
  </thead>
  <tbody>
  	<% @students.each do |std| %>
  	<tr>
  		<td>
        <%= link_to std  do%>
            <%= std.first_name + " " + std.last_name %>
          <% end %>
      </td>
  		<td><%= std.class_name %></td>
  		<td>
        <% 
          periods = Period.where(:student_id => std.id).where("state > 0")
          agg_periods = periods.group(['week_id', 'id'])
          agg_periods_abs= periods.where(:state => 2).group('week_id').count
          agg_periods_ret= periods.where(:state => 1).group('week_id').count
          tot_abs = periods.where(:state => 2).count
          tot_ret = periods.where(:state => 1).count
        %>

        <%=tot_ret%> 
      </td>
      <td><%=tot_abs%></td>
  	</tr>
  	<% end %>
  </tbody>
</table>

<%= link_to 'Gérer les étudiants', students_path%>

app/views/home/show_results.html.erb
<h4>Rapport des résultats</h4>


<ul class="nav nav-tabs">
<% @groups.each do |group| %>
	<li class="nav-item">
	    <% if group.id == @gr.to_i %>
	    	<%= link_to group.name, params.permit(:class).merge(:class => group.id) , class:"nav-link active" %>
	    <% else %>
	    	<%= link_to group.name, params.permit(:class).merge(:class => group.id) , class:"nav-link" %>
	    <% end %>
  	</li>
<% end %>
</ul>

<table class='table table-bordered table-striped table-responsive table-hover'>
  <thead class='table-dark'>
    <tr>
      <th>Étudiant</th>
      <th>Classe</th>
	  	<th class='text-center' colspan=<%= @tests.count %> >
	  		Épreuves
	    </th>
    </tr>
    <tr>
      <th></th>
      <th></th>
	  		<% @subjects.each do |sub| %>
  				<th class='text-center' colspan= <%= @tests.where(:subject_id => sub).count %> >
            		<%= Subject.find(sub).name %>
          </th>
      	<% end %>
    </tr>
  </thead>
  <tbody>
  	<tr>
  		<td></td>
  		<td></td>
  		<% @subjects.each do |sub| %>
  			<% i = 0 %>
  			<% @tests.where(:subject_id => sub).each do |t| %>
  				<td class='text-center'>
  					<% if t.test_type == 0 %>
  						<%= link_to  home_edit_results_path(:test_ids => [t.id]) do %>
            				<i class="bi bi-pencil-square"></i>
            			<% end %>
            		<% else %>
            			<%= link_to  home_edit_results_path(:test_ids => [t.id]) do %>
            				<i class="bi bi-chat"></i>
            			<% end %>
            		<% end %>
          </td>
      		<% end %>
      	<% end %>
  	</tr>
  	<% @students.each do |std| %>
  	<tr>
  		<td><%= std.first_name + " " + std.last_name %></td>
  		<td><%= std.class_name %></td>
  		<% @subjects.each do |sub| %>
  			<% @tests.where(:subject_id => sub).each do |t| %>
  				<td class='text-center'>
  					<% score = Score.where(:test_id => t.id).where(:student_id => std.id).first %>
  					<% if score.nil? or score.score.nil? %>
  						<span class="text-muted">na</span>
  					<%else%>
  						<% if score.score >= 4 %>
  							<span class="text-success"><%= score.score %></span>
  						<% else %>
  							<span class="text-danger"><%= score.score %></span>
  						<% end %>
  					<%end%>

          </td>
      		<% end %>
      	<% end %>
  	</tr>
  	<% end %>
  </tbody>
  <tfoot>
  	<tr>
  		<td></td>
  		<td></td>
  		<% @subjects.each do |sub| %>
  			<% @tests.where(:subject_id => sub).each do |t| %>
  				<td class='text-center'>
  					<% avg = Score.where(:test_id => t.id).average(:score) %>
            <% if avg.nil? %>
              <span class="text-muted">na</span>
            <%else%>
              <% if avg >= 4 %>
                <span class="text-success"><%= avg.round(2) %></span>
              <% else %>
                <span class="text-danger"><%= avg.round(2) %></span>
              <% end %>
            <%end%>
  				</td>
  			<% end %>
  		<% end %>
  	</tr>
  </tfoot>

  
</table>

<%= link_to 'Nouvelle épreuve', home_new_test_path, class:'btn btn-primary' %>
<br/>
<br/>
<%= link_to 'Gérer les branches', subjects_path%>
<br/>
<%= link_to 'Gérer les étudiants', students_path%>
<br/>
<%= link_to 'Gérer les épreuves', tests_path%>

app/views/home/timetable.html.erb
<h4> Classe <%=@requested_class.name%> Semaine <%= @requested_week.date_formated%></h4>
<br/>

<div class="card">
  <div class="card-header">
    <h4>Faire l'appel</h4>
  </div>
  <div class="card-body">

  	<span class="badge bg-warning text-dark">R: En retard</span>
	<span class="badge bg-danger text-dark">A: Absent</span>

  	<% days = ['Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi'] %>
	<%= render 'home/selection_day1' %>

	<%= form_tag discontinue_periods_path, remote:true,  method: :put do %>
		<%= render 'home/schedule' %>
	<% end %>
  </div>
</div>



<br/>

<%= render 'home/selection_week' %>

<br/>

<%= link_to 'Rapport', home_show_absences_path%>